var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var placeSchema = new mongoose.Schema({
    createdAt: {type: Date, default: Date.now},
    googleID: String,
    heatMap: {
	0: { 
		0:{ type: Number, min: 0, default: 0},
		1:{ type: Number, min: 0, default: 0},
		2:{ type: Number, min: 0, default: 0},
		3:{ type: Number, min: 0, default: 0},
		4:{ type: Number, min: 0, default: 0},
		5:{ type: Number, min: 0, default: 0},
		6:{ type: Number, min: 0, default: 0},
		7:{ type: Number, min: 0, default: 0},
		8:{ type: Number, min: 0, default: 0},
		9:{ type: Number, min: 0, default: 0},  
                10:{ type: Number, min: 0, default: 0},                             
                11:{ type: Number, min: 0, default: 0},
                12:{ type: Number, min: 0, default: 0},
                13:{ type: Number, min: 0, default: 0},
                14:{ type: Number, min: 0, default: 0},
                15:{ type: Number, min: 0, default: 0},
                16:{ type: Number, min: 0, default: 0},
                17:{ type: Number, min: 0, default: 0},
                18:{ type: Number, min: 0, default: 0},
		19:{ type: Number, min: 0, default: 0},          
                20:{ type: Number, min: 0, default: 0},                             
                21:{ type: Number, min: 0, default: 0},
                22:{ type: Number, min: 0, default: 0},
                23:{ type: Number, min: 0, default: 0}
	},	
	1: { 
		0:{ type: Number, min: 0, default: 0},
		1:{ type: Number, min: 0, default: 0},
		2:{ type: Number, min: 0, default: 0},
		3:{ type: Number, min: 0, default: 0},
		4:{ type: Number, min: 0, default: 0},
		5:{ type: Number, min: 0, default: 0},
		6:{ type: Number, min: 0, default: 0},
		7:{ type: Number, min: 0, default: 0},
		8:{ type: Number, min: 0, default: 0},
		9:{ type: Number, min: 0, default: 0},  
                10:{ type: Number, min: 0, default: 0},                             
                11:{ type: Number, min: 0, default: 0},
                12:{ type: Number, min: 0, default: 0},
                13:{ type: Number, min: 0, default: 0},
                14:{ type: Number, min: 0, default: 0},
                15:{ type: Number, min: 0, default: 0},
                16:{ type: Number, min: 0, default: 0},
                17:{ type: Number, min: 0, default: 0},
                18:{ type: Number, min: 0, default: 0},
		19:{ type: Number, min: 0, default: 0},          
                20:{ type: Number, min: 0, default: 0},                             
                21:{ type: Number, min: 0, default: 0},
                22:{ type: Number, min: 0, default: 0},
                23:{ type: Number, min: 0, default: 0}
	},
	2: { 
		0:{ type: Number, min: 0, default: 0},
		1:{ type: Number, min: 0, default: 0},
		2:{ type: Number, min: 0, default: 0},
		3:{ type: Number, min: 0, default: 0},
		4:{ type: Number, min: 0, default: 0},
		5:{ type: Number, min: 0, default: 0},
		6:{ type: Number, min: 0, default: 0},
		7:{ type: Number, min: 0, default: 0},
		8:{ type: Number, min: 0, default: 0},
		9:{ type: Number, min: 0, default: 0},  
                10:{ type: Number, min: 0, default: 0},                             
                11:{ type: Number, min: 0, default: 0},
                12:{ type: Number, min: 0, default: 0},
                13:{ type: Number, min: 0, default: 0},
                14:{ type: Number, min: 0, default: 0},
                15:{ type: Number, min: 0, default: 0},
                16:{ type: Number, min: 0, default: 0},
                17:{ type: Number, min: 0, default: 0},
                18:{ type: Number, min: 0, default: 0},
		19:{ type: Number, min: 0, default: 0},          
                20:{ type: Number, min: 0, default: 0},                             
                21:{ type: Number, min: 0, default: 0},
                22:{ type: Number, min: 0, default: 0},
                23:{ type: Number, min: 0, default: 0}
	},
	3: { 
		0:{ type: Number, min: 0, default: 0},
		1:{ type: Number, min: 0, default: 0},
		2:{ type: Number, min: 0, default: 0},
		3:{ type: Number, min: 0, default: 0},
		4:{ type: Number, min: 0, default: 0},
		5:{ type: Number, min: 0, default: 0},
		6:{ type: Number, min: 0, default: 0},
		7:{ type: Number, min: 0, default: 0},
		8:{ type: Number, min: 0, default: 0},
		9:{ type: Number, min: 0, default: 0},  
                10:{ type: Number, min: 0, default: 0},                             
                11:{ type: Number, min: 0, default: 0},
                12:{ type: Number, min: 0, default: 0},
                13:{ type: Number, min: 0, default: 0},
                14:{ type: Number, min: 0, default: 0},
                15:{ type: Number, min: 0, default: 0},
                16:{ type: Number, min: 0, default: 0},
                17:{ type: Number, min: 0, default: 0},
                18:{ type: Number, min: 0, default: 0},
		19:{ type: Number, min: 0, default: 0},          
                20:{ type: Number, min: 0, default: 0},                             
                21:{ type: Number, min: 0, default: 0},
                22:{ type: Number, min: 0, default: 0},
                23:{ type: Number, min: 0, default: 0}
	},
	4: { 
		0:{ type: Number, min: 0, default: 0},
		1:{ type: Number, min: 0, default: 0},
		2:{ type: Number, min: 0, default: 0},
		3:{ type: Number, min: 0, default: 0},
		4:{ type: Number, min: 0, default: 0},
		5:{ type: Number, min: 0, default: 0},
		6:{ type: Number, min: 0, default: 0},
		7:{ type: Number, min: 0, default: 0},
		8:{ type: Number, min: 0, default: 0},
		9:{ type: Number, min: 0, default: 0},  
                10:{ type: Number, min: 0, default: 0},                             
                11:{ type: Number, min: 0, default: 0},
                12:{ type: Number, min: 0, default: 0},
                13:{ type: Number, min: 0, default: 0},
                14:{ type: Number, min: 0, default: 0},
                15:{ type: Number, min: 0, default: 0},
                16:{ type: Number, min: 0, default: 0},
                17:{ type: Number, min: 0, default: 0},
                18:{ type: Number, min: 0, default: 0},
		19:{ type: Number, min: 0, default: 0},          
                20:{ type: Number, min: 0, default: 0},                             
                21:{ type: Number, min: 0, default: 0},
                22:{ type: Number, min: 0, default: 0},
                23:{ type: Number, min: 0, default: 0}
	},
	5: { 
		0:{ type: Number, min: 0, default: 0},
		1:{ type: Number, min: 0, default: 0},
		2:{ type: Number, min: 0, default: 0},
		3:{ type: Number, min: 0, default: 0},
		4:{ type: Number, min: 0, default: 0},
		5:{ type: Number, min: 0, default: 0},
		6:{ type: Number, min: 0, default: 0},
		7:{ type: Number, min: 0, default: 0},
		8:{ type: Number, min: 0, default: 0},
		9:{ type: Number, min: 0, default: 0},  
                10:{ type: Number, min: 0, default: 0},                             
                11:{ type: Number, min: 0, default: 0},
                12:{ type: Number, min: 0, default: 0},
                13:{ type: Number, min: 0, default: 0},
                14:{ type: Number, min: 0, default: 0},
                15:{ type: Number, min: 0, default: 0},
                16:{ type: Number, min: 0, default: 0},
                17:{ type: Number, min: 0, default: 0},
                18:{ type: Number, min: 0, default: 0},
		19:{ type: Number, min: 0, default: 0},          
                20:{ type: Number, min: 0, default: 0},                             
                21:{ type: Number, min: 0, default: 0},
                22:{ type: Number, min: 0, default: 0},
                23:{ type: Number, min: 0, default: 0}
	},
	6: { 
		0:{ type: Number, min: 0, default: 0},
		1:{ type: Number, min: 0, default: 0},
		2:{ type: Number, min: 0, default: 0},
		3:{ type: Number, min: 0, default: 0},
		4:{ type: Number, min: 0, default: 0},
		5:{ type: Number, min: 0, default: 0},
		6:{ type: Number, min: 0, default: 0},
		7:{ type: Number, min: 0, default: 0},
		8:{ type: Number, min: 0, default: 0},
		9:{ type: Number, min: 0, default: 0},  
                10:{ type: Number, min: 0, default: 0},                             
                11:{ type: Number, min: 0, default: 0},
                12:{ type: Number, min: 0, default: 0},
                13:{ type: Number, min: 0, default: 0},
                14:{ type: Number, min: 0, default: 0},
                15:{ type: Number, min: 0, default: 0},
                16:{ type: Number, min: 0, default: 0},
                17:{ type: Number, min: 0, default: 0},
                18:{ type: Number, min: 0, default: 0},
		19:{ type: Number, min: 0, default: 0},          
                20:{ type: Number, min: 0, default: 0},                             
                21:{ type: Number, min: 0, default: 0},
                22:{ type: Number, min: 0, default: 0},
                23:{ type: Number, min: 0, default: 0}
	}
    },
    current: { type: Number, min: 0, default: 0},
});

mongoose.model('Place', placeSchema);
